/**
 * Test Report Generator
 * Generates markdown reports from test results
 */

const fs = require('fs');
const path = require('path');

class TestReportGenerator {
  constructor() {
    this.timestamp = new Date().toISOString();
    this.reportPath = path.join(__dirname, '../test-results/TEST_REPORT.md');
  }

  /**
   * Generate comprehensive test report
   */
  async generateReport() {
    const playwrightResults = this.loadPlaywrightResults();
    const jestResults = this.loadJestResults();

    const report = this.buildMarkdownReport(playwrightResults, jestResults);

    // Ensure directory exists
    const dir = path.dirname(this.reportPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(this.reportPath, report);
    console.log(`\n✅ Test report generated: ${this.reportPath}\n`);
  }

  /**
   * Load Playwright test results
   */
  loadPlaywrightResults() {
    const resultsPath = path.join(__dirname, '../test-results/playwright-results.json');
    
    if (!fs.existsSync(resultsPath)) {
      return null;
    }

    try {
      const data = fs.readFileSync(resultsPath, 'utf-8');
      return JSON.parse(data);
    } catch (error) {
      console.error('Error loading Playwright results:', error);
      return null;
    }
  }

  /**
   * Load Jest test results
   */
  loadJestResults() {
    // Jest results would typically be in a JSON file if configured
    return null;
  }

  /**
   * Build markdown report
   */
  buildMarkdownReport(playwrightResults, jestResults) {
    let markdown = '';

    // Header
    markdown += `# NextDocs Test Report\n\n`;
    markdown += `**Generated:** ${new Date(this.timestamp).toLocaleString()}\n\n`;
    markdown += `---\n\n`;

    // Executive Summary
    markdown += `## Executive Summary\n\n`;
    
    if (playwrightResults) {
      const stats = this.calculatePlaywrightStats(playwrightResults);
      markdown += `### E2E Tests (Playwright)\n\n`;
      markdown += `- **Total Tests:** ${stats.total}\n`;
      markdown += `- **Passed:** ✅ ${stats.passed}\n`;
      markdown += `- **Failed:** ❌ ${stats.failed}\n`;
      markdown += `- **Skipped:** ⏭️ ${stats.skipped}\n`;
      markdown += `- **Success Rate:** ${stats.successRate}%\n`;
      markdown += `- **Duration:** ${stats.duration}ms\n\n`;
    } else {
      markdown += `### E2E Tests (Playwright)\n\n`;
      markdown += `⚠️ No Playwright results found. Run \`npm run test:e2e\` to generate results.\n\n`;
    }

    if (jestResults) {
      markdown += `### Unit/Integration Tests (Jest)\n\n`;
      markdown += `⚠️ Jest results integration pending.\n\n`;
    } else {
      markdown += `### Unit/Integration Tests (Jest)\n\n`;
      markdown += `⚠️ No Jest results found. Run \`npm run test:cli\` to generate results.\n\n`;
    }

    markdown += `---\n\n`;

    // Detailed Results
    if (playwrightResults) {
      markdown += this.buildPlaywrightDetailedReport(playwrightResults);
    }

    // Test Coverage Summary
    markdown += `## Test Coverage\n\n`;
    markdown += `### Functional Areas Tested\n\n`;
    markdown += `- ✅ Authentication & Authorization\n`;
    markdown += `- ✅ Homepage & Navigation\n`;
    markdown += `- ✅ Documentation Viewing\n`;
    markdown += `- ✅ Global Search\n`;
    markdown += `- ✅ Blog Posts\n`;
    markdown += `- ✅ API Specifications\n`;
    markdown += `- ✅ Feature Requests\n`;
    markdown += `- ✅ Admin Panel\n`;
    markdown += `- ✅ Database Integrity\n`;
    markdown += `- ✅ Search Functionality\n`;
    markdown += `- ✅ Repository Sync\n`;
    markdown += `- ✅ Content Management\n\n`;

    // Recommendations
    markdown += `---\n\n`;
    markdown += `## Recommendations\n\n`;
    
    if (playwrightResults) {
      const stats = this.calculatePlaywrightStats(playwrightResults);
      if (stats.failed > 0) {
        markdown += `- ⚠️ ${stats.failed} E2E test(s) failed. Review failures and fix issues.\n`;
      } else {
        markdown += `- ✅ All E2E tests passed successfully.\n`;
      }
    }

    markdown += `- 🔄 Run tests regularly in CI/CD pipeline\n`;
    markdown += `- 📊 Monitor test performance and duration\n`;
    markdown += `- 🎯 Add more edge case scenarios\n`;
    markdown += `- 🔍 Increase code coverage for critical paths\n\n`;

    // Footer
    markdown += `---\n\n`;
    markdown += `## Next Steps\n\n`;
    markdown += `1. Review failed tests and fix issues\n`;
    markdown += `2. Add missing test coverage for new features\n`;
    markdown += `3. Update test documentation\n`;
    markdown += `4. Run full test suite before deployment\n\n`;

    markdown += `---\n\n`;
    markdown += `*Report generated by NextDocs Test Suite*\n`;

    return markdown;
  }

  /**
   * Calculate Playwright statistics
   */
  calculatePlaywrightStats(results) {
    const suites = results.suites || [];
    let total = 0;
    let passed = 0;
    let failed = 0;
    let skipped = 0;
    let duration = 0;

    const countTests = (suite) => {
      if (suite.specs) {
        suite.specs.forEach(spec => {
          spec.tests.forEach(test => {
            total++;
            duration += test.results[0]?.duration || 0;
            
            const status = test.results[0]?.status;
            if (status === 'passed') passed++;
            else if (status === 'failed') failed++;
            else if (status === 'skipped') skipped++;
          });
        });
      }
      
      if (suite.suites) {
        suite.suites.forEach(countTests);
      }
    };

    suites.forEach(countTests);

    const successRate = total > 0 ? ((passed / total) * 100).toFixed(2) : 0;

    return { total, passed, failed, skipped, successRate, duration };
  }

  /**
   * Build detailed Playwright report
   */
  buildPlaywrightDetailedReport(results) {
    let markdown = `## Detailed Test Results\n\n`;

    const suites = results.suites || [];

    const processSuite = (suite, level = 3) => {
      const heading = '#'.repeat(level);
      markdown += `${heading} ${suite.title}\n\n`;

      if (suite.specs) {
        suite.specs.forEach(spec => {
          spec.tests.forEach(test => {
            const status = test.results[0]?.status;
            const icon = status === 'passed' ? '✅' : status === 'failed' ? '❌' : '⏭️';
            const duration = test.results[0]?.duration || 0;
            
            markdown += `- ${icon} **${spec.title}**\n`;
            markdown += `  - Status: ${status}\n`;
            markdown += `  - Duration: ${duration}ms\n`;

            if (status === 'failed' && test.results[0]?.error) {
              markdown += `  - Error: \`${test.results[0].error.message}\`\n`;
            }

            markdown += `\n`;
          });
        });
      }

      if (suite.suites) {
        suite.suites.forEach(s => processSuite(s, level + 1));
      }
    };

    suites.forEach(suite => processSuite(suite));

    return markdown;
  }
}

// Run report generation
const generator = new TestReportGenerator();
generator.generateReport().catch(console.error);

module.exports = TestReportGenerator;
