openapi: 3.0.3
info:
  title: NextDocs API
  description: |
    Enterprise Documentation Platform API for Harvey Norman Commercial Apps Team.
    
    This API provides programmatic access to documentation content, blog posts, 
    API specifications, and administrative functions for managing the documentation platform.
    
    ## Authentication
    All endpoints require authentication via Azure AD SSO or local credentials.
    Use Bearer token authentication with JWT tokens.
    
    ## Rate Limiting
    API requests are limited to 1000 requests per hour per user.
    
  version: 1.0.0
  contact:
    name: Harvey Norman Commercial Apps Team
    email: apps@harveynorman.com
  license:
    name: Proprietary
    url: https://harveynorman.com/license

servers:
  - url: http://localhost:9980/api
    description: Development server
  - url: https://docs.harveynorman.com/api
    description: Production server

tags:
  - name: Documentation
    description: Documentation content operations
  - name: Blog
    description: Blog post operations
  - name: Search
    description: Search and discovery
  - name: Admin
    description: Administrative operations (requires admin role)
  - name: Repositories
    description: Content repository management
  - name: API Specs
    description: API specification management
  - name: SSO
    description: SSO provider configuration

paths:
  /docs:
    get:
      tags:
        - Documentation
      summary: List all documentation categories
      description: Retrieve a list of all documentation categories with metadata
      operationId: listDocCategories
      parameters:
        - name: category
          in: query
          description: Filter by category slug
          schema:
            type: string
        - name: includeContent
          in: query
          description: Include full content in response
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  categories:
                    type: array
                    items:
                      $ref: '#/components/schemas/DocCategory'
                  total:
                    type: integer
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /docs/{category}/{slug}:
    get:
      tags:
        - Documentation
      summary: Get documentation page
      description: Retrieve a specific documentation page by category and slug
      operationId: getDocPage
      parameters:
        - name: category
          in: path
          required: true
          description: Category slug (e.g., dynamics-365-bc)
          schema:
            type: string
        - name: slug
          in: path
          required: true
          description: Page slug (e.g., financial-management)
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocPage'
        '404':
          description: Page not found
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /blog:
    get:
      tags:
        - Blog
      summary: List blog posts
      description: Retrieve a paginated list of blog posts
      operationId: listBlogPosts
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
            maximum: 100
        - name: tag
          in: query
          description: Filter by tag
          schema:
            type: string
        - name: author
          in: query
          description: Filter by author slug
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  posts:
                    type: array
                    items:
                      $ref: '#/components/schemas/BlogPost'
                  pagination:
                    $ref: '#/components/schemas/Pagination'

  /blog/{year}/{month}/{slug}:
    get:
      tags:
        - Blog
      summary: Get blog post
      description: Retrieve a specific blog post
      operationId: getBlogPost
      parameters:
        - name: year
          in: path
          required: true
          schema:
            type: string
        - name: month
          in: path
          required: true
          schema:
            type: string
        - name: slug
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlogPost'
        '404':
          description: Post not found

  /search:
    get:
      tags:
        - Search
      summary: Search content
      description: Full-text search across documentation and blog posts
      operationId: searchContent
      parameters:
        - name: q
          in: query
          required: true
          description: Search query
          schema:
            type: string
        - name: type
          in: query
          description: Content type filter
          schema:
            type: string
            enum: [docs, blog, all]
            default: all
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/SearchResult'
                  total:
                    type: integer

  /admin/repos:
    get:
      tags:
        - Admin
        - Repositories
      summary: List content repositories
      description: List all configured content repositories (admin only)
      operationId: listRepositories
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Repository'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'

    post:
      tags:
        - Admin
        - Repositories
      summary: Create content repository
      description: Add a new content repository (admin only)
      operationId: createRepository
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RepositoryInput'
      responses:
        '201':
          description: Repository created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Repository'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'

  /admin/repos/{id}/sync:
    post:
      tags:
        - Admin
        - Repositories
      summary: Sync repository
      description: Trigger manual sync of repository content
      operationId: syncRepository
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Sync initiated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyncLog'

  /admin/sso:
    get:
      tags:
        - Admin
        - SSO
      summary: List SSO providers
      description: List all configured SSO providers (admin only)
      operationId: listSSOProviders
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SSOProvider'

    post:
      tags:
        - Admin
        - SSO
      summary: Create SSO provider
      description: Add a new SSO provider (admin only)
      operationId: createSSOProvider
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SSOProviderInput'
      responses:
        '201':
          description: SSO provider created

  /admin/api-specs:
    get:
      tags:
        - Admin
        - API Specs
      summary: List API specifications
      description: List all API specifications (admin only)
      operationId: listAPISpecs
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/APISpec'

    post:
      tags:
        - Admin
        - API Specs
      summary: Create API specification
      description: Add a new API specification (admin only)
      operationId: createAPISpec
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/APISpecInput'
      responses:
        '201':
          description: API spec created

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    DocCategory:
      type: object
      properties:
        slug:
          type: string
          example: dynamics-365-bc
        title:
          type: string
          example: Dynamics 365 BC
        description:
          type: string
        icon:
          type: string
        order:
          type: integer
        pages:
          type: array
          items:
            type: object
            properties:
              slug:
                type: string
              title:
                type: string

    DocPage:
      type: object
      properties:
        slug:
          type: string
        title:
          type: string
        description:
          type: string
        content:
          type: string
          description: Markdown content
        category:
          type: string
        tags:
          type: array
          items:
            type: string
        lastUpdated:
          type: string
          format: date-time
        tableOfContents:
          type: array
          items:
            type: object

    BlogPost:
      type: object
      properties:
        slug:
          type: string
        title:
          type: string
        description:
          type: string
        content:
          type: string
        date:
          type: string
          format: date
        authors:
          type: array
          items:
            $ref: '#/components/schemas/Author'
        tags:
          type: array
          items:
            type: string
        image:
          type: string
          nullable: true
        featured:
          type: boolean

    Author:
      type: object
      properties:
        slug:
          type: string
        name:
          type: string
        title:
          type: string
        email:
          type: string
        bio:
          type: string
        avatar:
          type: string
        social:
          type: object

    SearchResult:
      type: object
      properties:
        type:
          type: string
          enum: [doc, blog]
        title:
          type: string
        description:
          type: string
        url:
          type: string
        highlights:
          type: array
          items:
            type: string

    Repository:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        provider:
          type: string
          enum: [azure-devops, github]
        url:
          type: string
        branch:
          type: string
        contentPath:
          type: string
        syncSchedule:
          type: string
        lastSync:
          type: string
          format: date-time
        status:
          type: string
          enum: [active, error, syncing]

    RepositoryInput:
      type: object
      required:
        - name
        - provider
        - url
        - pat
      properties:
        name:
          type: string
        provider:
          type: string
          enum: [azure-devops, github]
        url:
          type: string
        branch:
          type: string
          default: main
        contentPath:
          type: string
          default: /docs
        pat:
          type: string
          description: Personal Access Token (encrypted)
        syncSchedule:
          type: string
          default: 0 */1 * * *

    SSOProvider:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        provider:
          type: string
          enum: [azure-ad, google, okta]
        enabled:
          type: boolean
        domainRestriction:
          type: string

    SSOProviderInput:
      type: object
      required:
        - name
        - provider
        - clientId
        - clientSecret
      properties:
        name:
          type: string
        provider:
          type: string
          enum: [azure-ad, google, okta]
        clientId:
          type: string
        clientSecret:
          type: string
        tenantId:
          type: string
        domainRestriction:
          type: string

    APISpec:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        version:
          type: string
        specUrl:
          type: string
        renderer:
          type: string
          enum: [swagger-ui, redoc]
        category:
          type: string

    APISpecInput:
      type: object
      required:
        - name
        - version
        - specUrl
      properties:
        name:
          type: string
        description:
          type: string
        version:
          type: string
        specUrl:
          type: string
        renderer:
          type: string
          enum: [swagger-ui, redoc]
          default: swagger-ui
        category:
          type: string

    SyncLog:
      type: object
      properties:
        id:
          type: string
        repositoryId:
          type: string
        status:
          type: string
          enum: [pending, running, completed, failed]
        startedAt:
          type: string
          format: date-time
        completedAt:
          type: string
          format: date-time
        filesProcessed:
          type: integer
        error:
          type: string
          nullable: true

    Pagination:
      type: object
      properties:
        page:
          type: integer
        limit:
          type: integer
        total:
          type: integer
        totalPages:
          type: integer

  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Unauthorized

    ForbiddenError:
      description: User does not have permission to access this resource
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Forbidden
